//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "license")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub holder: String,
    pub expiry: DateTimeUtc,
    #[sea_orm(column_type = "JsonBinary")]
    pub extra_data: Json,
    pub policy_limit_connections: Option<i32>,
    pub app: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::App",
        to = "super::app::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    App,
    #[sea_orm(has_many = "super::license_log::Entity")]
    LicenseLog,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::license_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LicenseLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
