//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::admin_key::Entity as AdminKey;
pub use super::app::Entity as App;
pub use super::license::Entity as License;
pub use super::license_log::Entity as LicenseLog;
